[package]
name = "assets"
version = "0.1.0"
edition = "2021"

[dependencies]
tobj = "4.0.2"
common = { path = "../common" }
nalgebra = { workspace = true }
nalgebra-glm = { workspace = true }
image = { workspace = true }
rendering_backend = { path = "../rendering_backend" }
