[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
rendering_backend = { path = "../rendering_backend" }
material = {path = "../material"}
scene = {path = "../scene"}
assets = {path = "../assets"}
nalgebra-glm = { workspace = true }