[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
rendering_backend = { path = "../rendering_backend" }
material = { path = "../material" }
assets = { path = "../assets" }
core = { path = "../core" }
ecs = { path = "../ecs" }
nalgebra-glm = { workspace = true }