[package]
name = "scene"
version = "0.1.0"
edition = "2021"

[dependencies]
assets = { path = "../assets" }
rendering_backend = { path = "../rendering_backend" }
macros = { path = "../macros" }
material = { path = "../material" }
core = { path = "../core" }