[package]
name = "material"
version = "0.1.0"
edition = "2021"

[dependencies]
assets = { path = "../assets" }
nalgebra-glm = { workspace = true }
bitflags = "2.10.0"
serde = { version = "1.0.217", features = ["derive"] }
