[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
legacy_macros = { path = "../legacy_macros" }
nalgebra-glm = { workspace = true }
ecs = { path = "../ecs" }
assets = { path = "../assets" }
material = { path = "../material" }
input = { path = "../input" }